name: Sync Fork with Release

on:
  schedule:
    - cron: '0,30 11-19 * * MON-FRI'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: quartetcipp
          base: main
          head: main
